name: Setup Deno environment

on: 
  workflow_dispatch:
    inputs:
      denoVersion:
        description: 'Deno Version'     
        required: true
        default: '1.3.2'
      denoWorkerVersion:
        description: 'Deno Worker Version'
        required: true
        default: 'preview'
